agent_name: tim
author: eightballer
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.57.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections: []
contracts:
- eightballer/test:0.1.0:bafybeigpntmw6u5ofjgjc4t6q52hldppgoityzut34scldcjqxe4safgmu
protocols:
- open_aea/signing:1.0.0:bafybeihv62fim3wl2bayavfcg3u5e5cxu3b7brtu4cn5xoxd6lqwachasi
skills: []
customs: []
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
