name: 'publish'

on:
  push:
    branches:
      - release
  workflow_dispatch:
  # push:
  #   branches: [ master, main ]
  # pull_request:
  #   branches: [ master, main ]


jobs:
  build-docker:
    # Docker
    env:
      DOCKER_BUILDKIT: 1
      RELEASE_VERSION: 0.1.2
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}

    # Needed
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: 'macos-latest'
          args: '--target aarch64-apple-darwin'
          docker_platform: 'linux/arm64'
          tag_suffix: 'darwin-arm64'

        - os: 'macos-latest'
          args: '--target x86_64-apple-darwin'
          docker_platform: 'linux/amd64'
          tag_suffix: 'darwin-amd64'

        - os: 'ubuntu-22.04'
          args: '--target x86_64-unknown-linux-gnu'
          docker_platform: 'linux/amd64'
          tag_suffix: 'linux-amd64'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build platform specific image using buildx
        run: |
          export PLATFORM_TAG=$(echo ${{ matrix.docker_platform }} | tr '/' '-')
          docker buildx build \
            --platform=${{ matrix.docker_platform }} \
            --tag $IMAGE_NAME:${RELEASE_VERSION}  \
            --tag $IMAGE_NAME:latest \
            --push \
            .
        shell: bash